# Generated by Django 3.0.5 on 2020-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('userphone', models.CharField(max_length=100)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
