# Generated by Django 3.0.5 on 2020-05-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asebeza', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asebeza',
            name='product_type',
        ),
        migrations.AddField(
            model_name='asebeza',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asebeza.category'),
        ),
    ]
