# Generated by Django 3.0.5 on 2020-05-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asebeza', '0003_auto_20200528_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asebeza',
            name='mainimage',
        ),
    ]
