# Generated by Django 3.0.5 on 2020-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asebeza', '0004_remove_asebeza_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='asebeza',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
