# Generated by Django 3.0.5 on 2020-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asebeza', '0005_asebeza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asebeza',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery/products'),
        ),
    ]
