# Generated by Django 3.0.5 on 2020-05-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asebeza', '0006_auto_20200530_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asebeza',
            old_name='image',
            new_name='mainimage',
        ),
    ]
