# Generated by Django 3.0.5 on 2020-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsed',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searched',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
